CREATE DATABASE CVM
GO

USE CVM
GO

CREATE TABLE dbo.fundo_diario(
	CNPJ_FUNDO VARCHAR(14) NOT NULL,
	DT_COMPTC DATE NOT NULL,
	VL_TOTAL FLOAT NULL,
	VL_QUOTA FLOAT NULL,
	VL_PATRIM_LIQ FLOAT NULL,
	CAPTC_DIA FLOAT NULL,
	RESG_DIA FLOAT NULL,
	NR_COTST INT NULL,
	TP_FUNDO VARCHAR(30) NOT NULL,
	CO_PRD VARCHAR(14) NOT NULL,
	DT_REF DATE NOT NULL,
	PC_RESG FLOAT NULL,
	IdRegiao int NOT NULL,
	CONSTRAINT PK_fundo_diario PRIMARY KEY (CO_PRD, DT_REF)
)
GO
